name: ci cd pipeline
on: push
env:
  ARTIFACT_NAME: "cicd pipeline"
  
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        
      - name: run the python script
        run: python3 test.py
        
  Build:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: checkout the repo
        uses: actions/checkout@v2
        
      - name: create the artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
          
      
      
  
